package com.paku.mavlinkhub.enums;

public enum APP_STATE {

	MSG_SERVER_STARTED, MSG_SERVER_STOPPED, MSG_SERVER_CLIENT_CONNECTED, MSG_SERVER_CLIENT_DISCONNECTED, MSG_DRONE_CONNECTION_FAILED, MSG_QUEUE_MSGITEM_READY, MSG_DATA_UPDATE_SYSLOG, MSG_DATA_UPDATE_BYTELOG, MSG_DATA_UPDATE_STATS, REQUEST_ENABLE_BT, MSG_DRONE_CONNECTED

}
