package com.paku.mavlinkhub.enums;

public enum CONNECTOR_STATE {

	MSG_CONN_SERVER_CLIENT_CONNECTED, MSG_CONN_BYTE_DATA_READY, MSG_CONN_CLOSED, MSG_CONN_SERVER_CLIENT_DISCONNECTED, //
	MSG_CONN_DRONE_CLIENT_LOST_CONNECTION, MSG_CONN_SERVER_STARTED, MSG_CONN_SERVER_START_FAILED

}
