package com.paku.mavlinkhub.enums;

public enum SOCKET_STATE {

	MSG_SOCKET_SERVER_CLIENT_CONNECTED, MSG_SOCKET_BYTE_DATA_READY, MSG_SOCKET_CLOSED, MSG_SOCKET_SERVER_CLIENT_DISCONNECTED, MSG_SOCKET_DRONE_CLIENT_LOST_CONNECTION, MSG_SOCKET_SERVER_STARTED

}
