package com.paku.mavlinkhub.enums;

public enum UI_MODE {

	UI_MODE_CREATED, UI_MODE_BT_OFF, UI_MODE_DISCONNECTED, UI_MODE_CONNECTED, UI_MODE_TURNING_ON, UI_MODE_STATE_ON, UI_MODE_STATE_OFF, UI_MODE_TURNING_OFF

}
